version: '3.8'

services:
  php-docker-app:
    build:
      context: ./Backend  # Ensure this points to the Backend directory
      dockerfile: Dockerfile  # Specify the Dockerfile if it's named exactly that
    container_name: Contact-manager
    ports:
      - "8101:8101"
    volumes:
      - ./Backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0-oracle # Compatible with ARM64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: contactManager
    volumes:
      - db-data:/var/lib/mysql
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro 
    networks:
      - app-network

  vue-app:
    build:
      context: ./frontend  # Point to the Vue.js frontend directory
      dockerfile: Dockerfile # Specify the Dockerfile if it's named exactly that
    container_name: vue-app
    ports:
      - "8100:80" # Expose the Vue app (default Nginx port)
    volumes:
      - ./frontend:/app
    depends_on:
      - php-docker-app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: